# Generated by Django 6.0.2 on 2026-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default-avatar-icon-of-social-media-user-vector.jpg', upload_to='user_avatar/'),
        ),
    ]
